environment:

  matrix:
    - PYTHON: "C:\\Python35"
      TOXENV: py35-test
    - PYTHON: "C:\\Python36"
      TOXENV: py36-test
    - PYTHON: "C:\\Python37"
      TOXENV: py37-test
    - PYTHON: "C:\\Python38"
      TOXENV: py38-test

install:
  - "%PYTHON%\\python.exe -V"
  - "%PYTHON%\\python.exe -m pip install tox"
  - "%PYTHON%\\python.exe -m pip freeze"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -vv -e %TOXENV%"
