# Config file for generating documentation with Doctr on travis-ci.com
dist: xenial
language: python
env:
  global:
    - COVERALLS_PARALLEL=true
matrix:
  fast_finish: true
  include:
    - name: Docs
      python: 3.8
      env:
        - DOCS="true"
        # Doctr deploy key
        - secure: "lx6hTlyx9ZS5SgZg/DVL08CnNmG/u2ZEHnSwP4zoiB+ZxjpzJvlW3FsJuwAimyJjPAQkanp893ZYVfHDxP0RfW/fKTwvr3eXzO8WdW+hGcMqErpgpFagsm9ii5qsC30m1JJSU3+5V+VQB38J40kR8ijpb43KcTwks4SSETN3T7HmpByfujLua22JXNxGNnhKv8LUWS/myGQY+50FLlIPzpV3MeSJfl9C6c2z/1tN1Tr52pmUmAk09eZIDuWSZ6UcDSg1XqzSXjnR94Ft2sBkR25oZv75PZtMBDFaKtLzjTUPVna33eQsy+VRelni5IAPcNeCdoixe6WoKvPAXjgE5uOHPxgDzoUKzOZY7FxcZwCSUid950iUyD9BPT1xEK6nnw/XnQ2p7W5iK+EcQf2MfnpNlQkdhl2gDD2UdcTWfqpjhqMBxIPx0uXys/WdZH8SRV8BhADFJ3YLUMczkZdfB6Zn3lxNQYVoqdnIqrxsSj5Db3LG6zu7s0+Z1RAXyMOc0qf7HwrKf27yKV4++jb7LHD97l6TvME+7D+abWcczmIWFDWmyOarg2baUO9uleTKfmgH5Hy6+2GmMo2MYhc2kgAihN6XcKY8jnukgYBL5Wag5fcCo5PUWhHgwhTV6qXaeEskEU1Qzd9aRlbdOGXdRrfXgVakiTj/g5jd0Kz3A10="
        - BINTRAY_USER=goerz
        - BINTRAY_SUBJECT=goerz
        - BINTRAY_REPO=doctr_versions_menu
        - BINTRAY_PACKAGE=doctr_versions_menu
        # BINTRAY_TOKEN:
        - secure: IdnVMQ3YKHWDGNiafA96+aik7sa+XM4F6QpFz9MiVsGVgVNS0mZvO5iDkxIK96APuAUJOc33+LbYo4kiHYyFqUjtHsNF3/DriLVcEjlHnePVe6tlbW7Z6tel2wBvegxyE0fLe87yaq/tGy9AENp9FvrRboIiusWdIa5upzRduBLiAZUgOe8AOiQBVxNYtkIrH5/CUepZUv/V8ELWeDSbP/UMSHOLehJJXVr00V2ZYWIRFlFx2UhkisiNkxXP2gDuzn/sL5eLNc47BnXoKWMVXGaR4EkJrlIZINXZVPunl+buzayzqqv5Q4UUxh7BN2LaQ4MeH3j+rU+cCYaBzumG5V8LnbS4eXf5IPoXnyoPc8fSDU9jf2XTGw866iD7fLsS3mz2ZHKaX6gGP1y2g3uCAEGJJckS/tCilJ6AxtZS+UBaNIIOahD2Pge1s6DkeM/f4yWWaY526nG5cbkT89KjaWevY1qQSHqglbG4FJr7Qx2J7cd9/iimEkE/SwUBbWq7r0UsITK64U5EwM+29ZuRMIUaxZZaBmjtilOO/y2noyxXODn/pofkJU1b6Vls5/wskawKNtGvCHN2Jrj/mEmYEOs1cP1Ajtyi95jmt1WFAwaSREaKXYUoWKkg0kibxXVMkCkspXWW8ZAlZg3+I50az6UXmIIq+U+S4ahcuf6nux4=
        - DOCTR_VERSIONS_MENU_DEBUG: true
        - DOCTR_VERSIONS_MENU_VERSIONS: '''(<branches> != (master, rtd-theme)), (<releases>)[:-1], rtd-theme, (<releases>)[-1], master'''
        - DOCTR_VERSIONS_MENU_LABEL: '''rtd-theme: v0.3.0 (rtd-theme)'''
        - DOCTR_VERSIONS_MENU_WARNING: '''unreleased: (<branches> != rtd-theme), <local-releases>'''
      addons:
        apt_packages:

install:
  # any failure stops the build
  - set -e
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - travis_wait source .travis/texlive/texlive_install.sh
  - pip install tox zip-files
  - pip freeze
  - printenv
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
  # any failure stops testing immediately
  - set -e
  - source .travis/doctr_build.sh
  - echo "DONE"
